version: '3.9'

services:
 postgres_db:
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: "user"
   POSTGRES_PASSWORD: "12345678"
   POSTGRES_DB: "mydb"
  volumes:
   - ~/db:/var/lib/postgresql/data
  privileged: true

 crud_test:
  build:
   context: ./CRUDTest
   dockerfile: Dockerfile
  restart: always
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - postgres_db